### PR TITLE
changing hidraw of controllers to 0600 to stop steam from hijacking

### PR DESCRIPTION
**Pull request by nicman23**
i do _not_ know C, this does indeed work. please check it over.

### CODE REVIEW

**Comment by DanielOgorchock** [comment]
I think the cleaner way to achieve this effect is to change `ret = hid_hw_start(hdev, HID_CONNECT_HIDRAW);` in hid-nintendo to `ret = hid_hw_start(hdev, 0);`

This may be what you were referring to in the issue you opened. It will remove the hidraw device, and steam won't mess things up anymore. It's probably fine for it to be that way in the dkms module for now until a more permanent solution is discovered between hid-nintendo/steam.

It's annoying because steam still won't recognize the evdev as an input, but that's the same when using firejail. For games not relying on steam's input system (like games using sdl2 directly), this should be fine. I've found though that if I run steam and hid-nintendo as-is (without any firejail or masking away HIDRAW), I can get things working with steam's input system after replugging the controller in a few times. It's flaky for it to start working though, so maybe just killing hidraw is preferable for now.

**Comment by nicman23** [comment]
hmm i do not know, i think joycond is more suited for the task to be honest as it already is root anyways and also touches evdev devices. there can be a configuration option to toggle it.

it might be better to leave support for hidraw in the kernel module.

**Comment by DanielOgorchock** [comment]
Thinking about this more, it's probably even simpler to do this via an optional udev rules file. The current rules are already modifying permissions on the evdevs themselves. It should be simple for us to remove uaccess from the hidraw devs. Maybe it can be gated by a simple cmake variable to decide whether or not to install that rule.

**Comment by nicman23** [comment]
yeah that approach is basically the same thing with no C code. although there might be other rules udev overriding them? steam in arch installs /usr/lib/udev/rules.d/70-steam-input.rules:


```
# Nintendo Switch Pro Controller over USB hidraw
KERNEL=="hidraw*", ATTRS{idVendor}=="057e", ATTRS{idProduct}=="2009", MODE="0660", TAG+="uaccess"
# Nintendo Switch Pro Controller over bluetooth hidraw
KERNEL=="hidraw*", KERNELS=="*057E:2009*", MODE="0660", TAG+="uaccess"

```

**Comment by DanielOgorchock** [comment]
I think I have a hacky idea to make it actually work with steam. joycond can create a uinput device for the pro controller (similar to what it does for the joycons, but simpler since it's only one evdev). We can set the product id to that of the joycon charging grip. Then steam should actually use the evdev.

**Comment by nicman23** [comment]
yea, it is a good idea to generalize the code anyways - making all controllers to use a created uinput device. wont games be confused though ?

**Comment by DanielOgorchock** [comment]
joycond now blocks steam's hidraw access via udev and supports pairing the procon as a uinput dev

**Pull request closed without merging**
