### PR TITLE
added man page

### PR DESCRIPTION
**Pull request by Witherking25**

### CODE REVIEW

**Comment by Witherking25** [comment]
also i am packaging this software to be put in the debian archive, and proper github releases would be useful for the watchfile.

**Comment by Witherking25** [comment]
https://mentors.debian.net/package/joycond/

**Comment by Witherking25** [comment]
feel free to make changes or add things to the man page as you see fit. it's your program after all

**Comment by Witherking25** [comment]
also systemd services should go under /lib and not /etc
systemd only looks in /etc because it lets system administrators put services in there that *override* services in /lib

**Comment by GavinDarkglider** [comment]
My biggest issue here, is that the service isnt systemd specific. Systemd is just supported by default, because of l4t-ubuntu. I have openrc boot scripts that will also start joycond, with no modification to the current code. All systemd really does is run the app, and restart it if it crashes. https://gitlab.com/bell07/gentoo-switch_overlay/-/blob/master/media-libs/joycond/files/joycond

**Comment by Witherking25** [comment]
The problem is that lintian yells at me for the file being under /etc and not /lib. Systems specific or not, the service file should go under /lib because services under /etc have priority over /lib so that people can override the service file without modifying the actual file

**Comment by Witherking25** [comment]
Oh an I forgot to mention that I’m packaging this to go in the Debian archive and services going under /lib is Debian standard.

**Comment by Witherking25** [comment]
```diff
- install(FILES systemd/joycond.service DESTINATION /etc/systemd/system
+ install(FILES systemd/joycond.service DESTINATION /lib/systemd/system
```

**Comment by Witherking25** [comment]
https://lintian.debian.org/tags/systemd-service-file-outside-lib.html

**Pull request merged**
